### ISSUE TITLE
Exponentiation and types

### ISSUE THREAD

**Issue by bluetooth-mdw** [mkrd/Swift-BigInt#41] opened 2019-09-03 14:18 UTC
Hi

The README contains the following:

```
// Exponentiation
BInt ** Int       // Retuns BInt to the power of Int
```

but I get a compilation error of "Cannot convert value of type 'BInt' to expected argument type 'BDouble'" from the following code. Am I doing something wrong or is the documentation or API at fault?

```
        let TWO : BInt = 2
        let TWO_SIX_THREE : Int = 263
        var TWO_POW_263 : BInt = TWO ** TWO_SIX_THREE
```

Thanks in anticipation

Martin

**Comment by twodayslate** [comment] 2019-09-04 00:17
What version of Swift are you using?

**Comment by bluetooth-mdw** [comment] 2019-09-04 05:33
Hi! I'm using version 5.

**Comment by twodayslate** [comment] 2019-09-04 15:08
Unable to reproduce https://github.com/mkrd/Swift-BigInt/commit/0b353aa84f2a4c0de499f496ce8d551f07bd8d9c#diff-733881c122a9299bec8512e3fc2fec48

**Comment by mkrd** [comment] 2019-12-10 21:59
Possibly [https://github.com/mkrd/Swift-BigInt/blob/6a379be3125065d50bf15648f7223be351721ca8/Sources/Swift-Big-Number-Core.swift#L842](url).
The BDouble equivalent is declared as public, while this is not.
It is weird that the problem is not reproducible, but declaring the function as public might solve the issue

**Comment by twodayslate** [comment] 2020-08-27 19:56
Closing as I believe this is resolved

**Closed by twodayslate** 2020-08-27 19:56 UTC
